[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Impostazioni per la sicurezza e performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache per le immagini (1 anno)
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache per HTML (1 ora)
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirect per SEO (se necessario)
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

# 404 personalizzata (opzionale)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
